# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_contest_check_script'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='scoring',
        ),
        migrations.AlterField(
            model_name='contest',
            name='check_script',
            field=models.TextField(default='#given_path, ground_path, pandas as pd, metrics, are variables available', help_text='script to check and set the score variable to an appropriate value'),
        ),
        migrations.DeleteModel(
            name='ScoreSchemes',
        ),
    ]
