# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_contest_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='reverse_lb',
            field=models.BooleanField(default=True, help_text='Leaderboard must be sorted highest metric first?'),
        ),
    ]
